apiVersion: v2
name: vm
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: victoria-metrics-k8s-stack
    version: "0.45.0"
    repository: "https://victoriametrics.github.io/helm-charts"
  - name: victoria-logs-single
    version: "0.11.25"
    repository: "https://victoriametrics.github.io/helm-charts"
  - name: fluent-bit
    version: "0.47.0"
    repository: "https://fluent.github.io/helm-charts"