apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-frontend-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "mychart.fullname" . }}-frontend
  ports:
    - protocol: {{ .Values.frontend.service.ports.protocol }}
      port: {{ .Values.frontend.service.ports.port }}
      targetPort:  {{ .Values.frontend.service.ports.targetPort }}