apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432