apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
# Кожне значення буде перетворено в base64 у кластері при деплої тому паролів і логінів не буде видно,
# видно тільки зараз у репозиторії 
# (наприклад, через команду echo -n "..." | base64)
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "postgres"