Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "jenkins", primary: true do |jk|
    jk.vm.hostname = "jenkins"
    jk.vm.network "private_network", ip: "192.168.50.33"
    
    jk.vm.provider "virtualbox" do |vb|
      vb.name = "jenkins"
      vb.memory = 2048
      vb.cpus = 2
    end
    
    jk.vm.provision "shell", inline: <<-SHELL
      apt-get update && apt-get upgrade -y
      apt-get install -y net-tools
    SHELL
  end

  config.vm.define "slave" do |slave|
    slave.vm.hostname = "slave"
    slave.vm.network "private_network", ip: "192.168.50.34"
    
    slave.vm.provider "virtualbox" do |vb|
      vb.name = "slave"
      vb.memory = 5120
      vb.cpus = 3
    end
    
    slave.vm.provision "shell", inline: <<-SHELL
      apt-get update && apt-get upgrade -y
      apt-get install -y net-tools
    SHELL
  end
  
  config.vm.define "ansible" do |ansible|
    ansible.vm.hostname = "ansible"
    ansible.vm.network "private_network", ip: "192.168.50.35"
    
    ansible.vm.provider "virtualbox" do |vb|
      vb.name = "ansible"
      vb.memory = 2048
      vb.cpus = 1
    end
    
    ansible.vm.provision "shell", inline: <<-SHELL
      apt-get update && apt-get upgrade -y
      apt-get install -y net-tools
    SHELL
  end
  
end